# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: VS2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      pushd "%VS140COMNTOOLS%..\..\VC" & call vcvarsall.bat amd64 & popd
      nmake
      nmake verify

- job: VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools" & call VsDevCmd.bat & popd
      nmake
      nmake verify

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: make
  - script: make verify

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt install -y flex
      make
      make --directory=scripts/installers/packagemaker
      make verify
    displayName: 'make'
