language: cpp

before_install:
  - pip install codecov

after_success:
  - codecov

compiler:
  - gcc
  - clang

script: make clean all test

branches:
  only:
    - master

notifications:
  email: false

env: PROG=

os:
  - linux
