language: cpp

compiler:
  - gcc
  - clang

script: make clean all test

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token CXXFLAGS=-coverage LDFLAGS=-coverage PROG=

os:
  - linux

install:
  - pip install --upgrade pip
  - pip install codecov

after_success:
  - codecov
