sudo: require
language: cpp

git:
  depth: false

branches:
  only:
    - master

notifications:
  email: false

jobs:
  include:
  - name: llvm-scan-build
    os: osx
    before_install:
    - sudo pip install scan-build
    compiler: clang
    env:
     - DEBUG=yes
     - SAFE_ONLY=yes
    script:
    - make clean
    - scan-build -v make dist

  - name: cpplint 
    os: osx
    before_install:
    - sudo pip install cpplint
    script:
    - make clean
    - cpplint --recursive --filter=-whitespace,-runtime,-build,-readability,-legal src

  - name: Code Coverage 
    os: linux
    env:
     - CXXFLAGS="-coverage -O0" LDFLAGS="-coverage -O0" DEBUG="yes" PROG=
    dist: xenial
    compiler: gcc
    before_install:
    - sudo pip install codecov
    after_success:
    - bash <(curl -s https://codecov.io/bash) -a "--object-directory=build/objects/x86_64-linux-g++5"
    script:
    - make clean
    - make coverage
    - codecov

  - name: linux-valgrind-memcheck-callgrind-cachegrind-ham4
    os: linux
    dist: xenial
    env:
     - SAFE_ONLY=yes
     - DEBUG=yes
    before_install:
    - sudo apt-get install -y valgrind
    compiler: gcc
    script:
    - make clean
    - make dist 
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-memcheck ham4
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-callgrind ham4
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-cachegrind ham4

  - name: linux-valgrind-memcheck-callgrind-cachegrind-bcb
    os: linux
    dist: xenial
    env:
     - SAFE_ONLY=yes
     - DEBUG=yes
    before_install:
    - sudo apt-get install -y valgrind
    compiler: gcc
    script:
    - make clean
    - make dist 
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-memcheck bcb
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-callgrind bcb
    - make --directory=examples PROG=../../../scripts/ci/run-valgrind-cachegrind bcb

  - os: windows
    install: choco install -y make
    env:
    - SAFE_ONLY=yes
    compiler: gcc
    script:
    - make.exe clean
    - make.exe dist
    - make.exe gtests

  - os: windows
    env:
    - SAFE_ONLY=yes
    script:
    - scripts/ci/travis-windows-vc-build.bat
