language: cpp

compiler:
  - gcc
  - clang

script: make clean all test

branches:
  only:
    - master

notifications:
  email: false

env:
  - CXXFLAGS=-coverage LDFLAGS=-coverage PROG=

os:
  - linux

before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
