language: cpp

compiler:
  - gcc
  - clang

script: make clean all test

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    - CXXFLAGS="-coverage -O0" LDFLAGS="-coverage -O0" DEBUG="yes" PROG=

os:
  - linux

after_success:
  - bash <(curl -s https://codecov.io/bash)
