sudo: require
language: cpp

git:
  depth: false

branches:
  only:
    - master

notifications:
  email: false

compiler:
  - gcc

os:
  - linux
  - macos

stages:
  - build
  - test

jobs:
  include:
  - stage: build
    script:
    - make clean dist
  - stage: test
    script:
    - make --directory=examples admb
