language: cpp

compiler:
  - gcc
  - clang

script: make clean all test

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token CXXFLAGS=-coverage LDFLAGS=-coverage PROG=

os:
  - linux

after_success:
  - bash <(curl -s https://codecov.io/bash)
