sudo: require
language: cpp

branches:
  only:
    - master

notifications:
  email: false

matrix:
  include:
  - os: linux
    env:
     - CXXFLAGS="-coverage -O0" LDFLAGS="-coverage -O0" DEBUG="yes" PROG=
    dist: xenial
    compiler: gcc
    before_install:
    - sudo pip install codecov
    after_success:
    - bash <(curl -s https://codecov.io/bash) -a "--object-directory=build/objects/debug"
    script:
    - make clean coverage
    - codecov

  - os: linux
    dist: xenial
    env:
     - CXXFLAGS="-O0" LDFLAGS="-O0" DEBUG="yes" PROG=
    compiler: gcc
    script:
    - make clean all

  - os: osx
    env:
     - CXXFLAGS="-O0" LDFLAGS="-O0" DEBUG="yes" PROG=
    compiler: clang
    script:
    - make clean all

  - os: osx
    env:
     - CXXFLAGS="-O0" LDFLAGS="-O0" DEBUG="yes" PROG=
    compiler: gcc
    script:
    - make clean all

  - os: windows
    env:
     - DEBUG="yes" PROG=
    compiler: gcc
    script:
    - utilities/make.exe clean all

  - os: windows
    env:
     - DEBUG="yes" PROG=
    compiler: msvc
    script:
    - utilities/make.exe clean all
