sudo: require
language: cpp

branches:
  only:
    - master

notifications:
  email: false

matrix:
  include:
  - os: linux
    env:
     - CXXFLAGS="-coverage -O0" LDFLAGS="-coverage -O0" DEBUG="yes" PROG=
    dist: xenial
    compiler: gcc
    before_install:
    - sudo pip install codecov
    after_success:
    - bash <(curl -s https://codecov.io/bash) -a "--object-directory=build/objects/debug"
    script:
    - make clean coverage
    - codecov

  - os: linux
    dist: xenial
    compiler: gcc
    script:
    - make clean
    - make dist 
    - make gtests

  - os: linux
    dist: xenial
    compiler: gcc
    script:
    - make clean
    - make

  - os: linux
    dist: xenial
    compiler: gcc
    script:
    - make clean
    - make dist 
    - make verify

  - os: linux
    dist: xenial
    compiler: gcc
    script:
    - make clean
    - make dist
    - make shared
    - make all

  - os: linux
    dist: xenial
    compiler: gcc
    script:
    - make clean
    - make shared
    - make dist
    - make all

  - os: osx
    env:
     - COVERAGE=yes DEBUG= PROG=
    compiler: clang
    script:
    - make clean dist test

  - os: osx
    env:
     - COVERAGE=yes DEBUG= PROG=
    compiler: gcc
    script:
    - make clean dist test

  - os: windows
    install: choco install -y make
    env:
    - COVERAGE=yes PROG=
    compiler: gcc
    script:
    - make.exe clean dist gtests

  - os: windows
    env:
    - COVERAGE=yes PROG=
    script:
    - utilities/travis-windows-vc-build.bat
