sudo: require
language: cpp

git:
  depth: false

branches:
  only:
    - master
    - coverity_scan

notifications:
  email: false

env:
  global:
    - secure:

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "admb-project/admb"
      description: "ADMB Project"
    notification_email: johnoel@hawaii.edu
    build_command_prepend: "make clean"
    build_command: "make dist test"
    branch_pattern: coverity_scan

matrix:
  - os: linux
    dist: xenial
    env:
     - SAFE_ONLY=yes
     - DEBUG=yes
    compiler: gcc
    script:
    - make clean
    - make dist 
    - make test
