sudo: require
language: cpp

env:
  global:
  - CXXFLAGS="-coverage -O0" LDFLAGS="-coverage -O0" DEBUG="yes" PROG=

branches:
  only:
    - master

notifications:
  email: false

matrix:
  include:
  - os: linux
    dist: xenial
    compiler:
    - gcc
    - clang
    before_install:
    - sudo pip install codecov
    after_success:
    - bash <(curl -s https://codecov.io/bash) -a "--object-directory=build/objects/debug"
    script:
    - make clean coverage
    - codecov

  - os: osx
    compiler:
    - gcc
    - clang
    script:
    - make clean all

  - os: windows
    script:
    - nmake clean all
