name: Ubuntu build of ADMB 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: flex
      run: sudo apt-get install flex
    - name: clean
      run: make clean
    - name: build
      run: make
    - name: tests
      run: make test
