name: macos-latest-dist

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: make clean
    - name: dist
      run: |
        make
    - name: shared
      run: |
        make shared
    - name: zip
      run: |
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_zip_distribution
        path: build/admb.zip
