name: ubuntu-latest-dist

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: make clean
    - name: build
      run: |
        make
        make DEBUG=yes
        make shared
        make shared DEBUG=yes
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_zip_distribution
        path: build/admb.zip
