name: ubuntu-latest-debug-32bit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: flex
      run: sudo apt-get install flex
    - name: clean
      run: make clean DEBUG=yes
    - name: build
      run: make DEBUG=yes CXXFLAGS=-m32
    - name: tests
      run: make test DEBUG=yes CXXFLAGS=-m32
