name: ubuntu-latest-shared-debug-64bit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: flex
      run: sudo apt-get install flex
    - name: clean
      run: make clean DEBUG=yes
    - name: build
      run: make shared DEBUG=yes
