name: windows-latest-debug

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: nmake clean DEBUG=yes
    - name: build
      run: nmake DEBUG=yes
    - name: tests
      run: nmake test DEBUG=yes
