name: windows-latest-dist-rtools40

on: [push]

jobs:
  build:

    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: |
        set PATH=C:\rtools40\mingw64\bin;%PATH%
        utilities\\make clean
      shell: cmd
    - name: rtool40 mingw64
      run: |
        set PATH=C:\rtools40\mingw64\bin;%PATH%
        utilities\\make
        utilities\\make shared
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_windows_latest_dist_rtools40
        path: build\\admb
