name: windows-latest-dist-rtools35-debug

on: [push]

jobs:
  build:

    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v1
    - name: clean
      run: |
        set PATH=C:\rtools35\mingw_64\bin;%PATH%
        utilities\\make clean
      shell: cmd
    - name: rtool35 mingw64
      run: |
        set PATH=C:\rtools35\mingw_64\bin;%PATH%
        utilities\\make DEBUG=yes
        utilities\\make DEBUG=yes shared
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_windows_latest_dist_rtools35_debug
        path: build\\admb
